import type { Metadata } from "next";
import { Arizonia, EB_Garamond } from "@next/font/google";

import "./globals.css";

const arizonia = Arizonia({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-arizonia",
});

const eb_garamond = EB_Garamond({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-eb-garamond",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${eb_garamond.variable} ${arizonia.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
